/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      nunito: ["Nunito", "sans-serif"],
      facultyGlyphic: ['"Faculty Glyphic"', "serif"], // Adaugă ghilimele pentru fonturi cu spații
      montserrat: ["Montserrat", "sans-serif"],
      dancingScript: ['"Dancing Script"', "serif"],
      ptSansNarrow: ['"PT Sans Narrow"'],
      edu: ['"Edu Australia VIC WA NT Hand Precursive"'],
    },
    extend: {
      colors: {
        forestgreen: "#228B22",
        mossgreen: "#8A9A5B",
        salmonpink: "#FF91A4",
        lightsalmon: "#FFA07A",
        darksalmon: "#E9967A",
        deepperiwinkle: "#5C6E91",
        softlilac: "#E4C6E7",
        softpeach: "#FFF2D7",
        teal: "#20948B",
        orangered: "#FB6542",
        cherryred: "#CC313D",
        mintgreen: "#98FF98",
        kellygreen: "#4CBB17",
        seashell: "#FFF5EE",
        bisque: "#F2D2BD",
        mulberry: "#770737",
        brightyellow: "#FFEA00",
        lightorange: "#FFD580",
        kaki: "#FBEC5D",
        cherry: "#D2042D",
        burgundy: "#800020",
        millenialpink: "#F3CFC6",
        eggshell: "#F0EAD6",
        beige: "#F5F5DC",
        cadmiumred: "#D22B2B",
        darkred: "#8B0000",
        bonewhite: "#F9F6EE",
        ivory: "#FFFFF0",
        offwhite: "#FAF9F6",
        linen: "#E9DCC9",
        nianza: "#ECFFDC",
        cadmiumRed: "#D22B2B",
      },
    },
  },
  plugins: [],
};
